---
ssh:
  accept_env: LANG LC_*
  allow_groups: adm
  allow_users:
  authorized_keys_file: '%h/.ssh/authorized_keys'
  challenge_response_authentication: 'no'
  client_alive_count_max: 0
  client_alive_interval: 300
  debian_banner: 'no'
  host_based_authentication: 'no'
  ignore_rhosts: 'yes'
  key_regeneration_interval: 3600
  login_grace_time: 10
  log_level: INFO
  password_authentication: 'no'
  permit_empty_passwords: 'no'
  permit_root_login: 'no'
  port: 22
  print_last_log: 'yes'
  print_motd: 'no'
  protocol: 2
  pub_key_authentication: 'yes'
  rhosts_rsa_authentication: 'no'
  rsa_authentication: 'yes'
  server_key_bits: 1024
  strict_modes: 'yes'
  sys_log_facility: AUTH
  tcp_keep_alive: 'yes'
  use_pam: 'yes'
  use_privilege_separation: 'yes'
  x11_forwarding: 'no'
  x11_display_offset: 10
